# Generated by Django 5.2.7 on 2025-10-07 10:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=191, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=191, null=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'um_user_profiles',
            },
        ),
        migrations.CreateModel(
            name='UserLoginTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=191, unique=True)),
                ('password_hash', models.CharField(max_length=191)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth', to='users.userprofiletbl')),
            ],
            options={
                'db_table': 'um_user_auths',
            },
        ),
        migrations.CreateModel(
            name='UserTokenTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=191, unique=True)),
                ('iat', models.DateTimeField(default=django.utils.timezone.now)),
                ('exp', models.DateTimeField(blank=True, null=True)),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='users.userlogintbl')),
            ],
            options={
                'db_table': 'um_user_tokens',
            },
        ),
    ]
